### ISSUE TITLE
Emissiebron onduidelijkheid in gebruik

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-omgeving#14]
Bij gebruik wordt vermeld:
Het kan een inrichting zijn zoals een fabriek, installatie of schoorsteen maar ook een activiteit zoals bemesting. 
Typisch onderworpen aan milieuwetgeving en opgelijst als potentieel hinderlijk, zie bv. IIOA's van VLAREM

- Worden hier niet IOA's bedoeld? VLAREM handelt vooral over IOA's, een IIOA is een bundeling van instances van IOA's, de vergunde eenheid.
- In IMJV heeft men het over gekoppelde activiteiten. Is zo'n gekoppelde activiteit dan de emissiebron en de meetput of lozingsplaats (die heeft een geo-component) het Meetpunt, dat via de property bemonsterdObject aan de gekoppelde activiteit/Emissiebron wordt gekoppeld?

**Comment by J-meirlaen** [comment]
Emissiebron is volgens mij op dit moment net bedoeld als een koepelbegrip. 
Je kan emissies rapporteren op het niveau van een bedrijf, van een IIOA, een installatie, een lozingspunt, een schouw,  maar evengoed van een land, een regio, of bekken.
Binnen de context van het waterkwaliteitsproject is er voor gekozen om hier geen verdere modellering te doen, omdat dit niet binnen de scope van het project paste. 
Het IMJV was op zich niet in scope van het project. Het enige wat gevraagd is, is om emissies per bedrijf te kunnen rapporteren.   en dat lijkt te kunnen, al moeten we nog even afwachten hoe Geert Thijs in het uitgewerkte voorbeeld hier mee omgaat.

De expliciete onderdelen van een bedrijf zoals beschouwd in het IMJV of in een vergunning, komen mogelijk aan bod in het project rond de omgevingsvergunning.

**Comment by gezever** [comment]
Ik ga deze sluiten als duplicate of https://github.com/Informatievlaanderen/OSLOthema-Waterkwaliteit/issues/21
