### ISSUE TITLE
TO DO: Checks Codelijst

### ISSUE THREAD

**Issue by VincentFeremans** [Informatievlaanderen/OSLOthema-omgeving#2]
Dag @gezever, 

Hieronder vind je nog enkele to do's:

- Notatie van de SMILES is niet correct (bv. zie Benzeen --> ontbreking van "='s" en hoofdletters). Kun je dit even nakijken?
- Groeperingen controleren --> in de tweede thematische werkgroep zijn er nieuwe groeperingen gemaakt:
1. Zuivere stof
2. Groepsparameter: Een parameter dat bekomen wordt als één meetresultaat als gevolg van een analysemethode.
3. Som: Een berekening of waarde waarbij verschillende metingen bij elkaar zijn opgeteld of afgetrokken.
4. Fysicochemische eigenschappen: bv. Temperatuur, korrelgrootte etc.

Kunnen de stoffen die als "mengsel" zijn geïdentificeerd allemaal onder 1 van de bovenstaande groeperingen worden gecategoriseerd? Indien ja, gelieve dit dan ook te doen. Verder stel ik ook voor om de stoffen die twee groepsidentificaties hebben gekregen van de participanten (bv. "mengsel in matrix lucht, zuivere stof (bij analyse)" voor de stof Lood) onder te categoriseren onder wat het bij analyse is. In dit voorbeeld dus onder zuivere stof. Wat denk jij?

- Ik zou zeker het verslag van de tweede thematische werkgroep nog even doornemen. Hier staan nog enkele andere comments in zoals o.a. de juiste notatie nemen voor het PrefLabel van de stof Ammoniak (in de formule moeten hoofdletters worden gebruikt ipv kleine letters). Aarzel niet om Arne te contacteren indien hier iets niet duidelijk is.

Alvast bedankt!

Met vriendelijke groeten,
Vincent

**Comment by gezever** [comment]
@VincentFeremans 
Zuivere stof, fysico-chemische eigenschappen enz. zijn volgens mij geen groepen, maar apparte lijsten. Huidige groepen zijn water en lucht als media waarin de stof gemeten wordt.

**Comment by gezever** [comment]
@VincentFeremans 
Ik vraag me af of hoofdletters bij prefLabels een goed idee is. Zonder een set regels kan ik dat niet doen.
vb. Wat met p-tolueensulfonamide? Is het de bedoeling dat dit P-tolueensulfonamide of p-Tolueensulfonamide of p-TolueenSulfonAmide wordt? Idem voor bis(2-chloorethyl)2-chloorethylfosfonaat, bijvoorbeeld.

**Comment by gezever** [comment]
prefLabel is slechts een annotationproperty.
