### ISSUE TITLE
Choorfenvinfos vs. cis-Chloorfenvinfos vs. trans-Chloorfenvinsfos

### ISSUE THREAD

**Issue by J-meirlaen** [Informatievlaanderen/OSLOthema-omgeving#24]
in de codelijsten zijn de parameter Chloorfenvinfos en cis-chloorfenvinfos samengevoegd.
Het gaat hier om twee verschillende concepten

Chloorfenvinfos ([https://pubchem.ncbi.nlm.nih.gov/compound/Chlorfenvinphos](https://pubchem.ncbi.nlm.nih.gov/compound/Chlorfenvinphos), CAS 470-90-6 ) is de som van 

- cis-chloorfenvinfos ([https://pubchem.ncbi.nlm.nih.gov/compound/5377784](https://pubchem.ncbi.nlm.nih.gov/compound/5377784), 18708-87-7) en 
- trans-chloorfenvinfos ([https://pubchem.ncbi.nlm.nih.gov/compound/5377791](https://pubchem.ncbi.nlm.nih.gov/compound/5377791), CAS 18708-86-6). 

Chloorfenvinfos moet toegevoegd worden aan de lijst sommatie stoffen.
Trans-chloorfenvinfos moet worden toegevoegd aan de chemische stoffen.

**Comment by gezever** [comment]
@J-meirlaen 
trans-cloorfenvinfos bestaat al
https://data.omgeving.vlaanderen.be/id/concept/chemische_stof/FSAVDKDHPDSCTO-XYOKQWHBSA-N

**Comment by gezever** [comment]
aangemaakt https://data.omgeving.vlaanderen.be/id/concept/sommatie_stoffen/clfvfs
