### ISSUE TITLE
Endrin en dieldrin zijn onterecht samengevoegd

### ISSUE THREAD

**Issue by J-meirlaen** [Informatievlaanderen/OSLOthema-omgeving#25]
De stoffen endrin en dieldrin zijn onterecht samengevoegd onder  
https://data.omgeving.vlaanderen.be/id/concept/chemische_stof/DFBKLUNHFCTMDC-UHFFFAOYSA-N

Endrin heeft CAS nummer 72-20-8 en pubchem https://pubchem.ncbi.nlm.nih.gov/compound/3048
Dieldrin heeft CAS nummer 60-57-1 en https://pubchem.ncbi.nlm.nih.gov/compound/969491

Kan Dieldrin bijgemaakt worden als chemische stof?
Kan het cas-nummer 60-57-1, het alt-label dieldrin en de notation dieldn geschrapt worden bij Endrin?

**Comment by gezever** [comment]
dieldrin: https://data.omgeving.vlaanderen.be/id/concept/chemische_stof/DFBKLUNHFCTMDC-PICURKEMSA-N

endrin: https://data.omgeving.vlaanderen.be/id/concept/chemische_stof/DFBKLUNHFCTMDC-UHFFFAOYSA-N
