### ISSUE TITLE
beta-hexachloorcyclohexaan heeft een foute naam

### ISSUE THREAD

**Issue by J-meirlaen** [Informatievlaanderen/OSLOthema-omgeving#26]
https://data.omgeving.vlaanderen.be/id/concept/chemische_stof/JLYXXMFPNIAWKQ-UHFFFAOYSA-N heeft als preflabel beta-hexachloorcyclohexaan, maar verwijst naar een stof die op pubchem (https://pubchem.ncbi.nlm.nih.gov/compound/727) verwijst naar de verschillende isomeren, waardoor de prefLabel eigenlijk foutief is. 
Graag het preflabel wijzigen naar Hexachloorcyclohexaan.

Volgens https://commonchemistry.cas.org/detail?cas_rn=58-89-9 zijn volgende cas-nummers niet meer actief, en mogen die dus vermoedelijk ook geschrapt worden
Deleted or Replaced CAS Registry Numbers
8007-42-9, 8073-23-2, 25897-48-7, 53529-37-6, 55963-79-6

**Comment by gezever** [comment]
@J-meirlaen 
Ik verwijder die cas nummers, maar ik vermoed dat die ergens in de regelgeving staan om naar lindaan te verwijzen, anders zouden die hier toch niet gebruikt worden?

**Comment by J-meirlaen** [comment]
@gezever 
ik heb Vlarem afgezocht en daar vind ik alleen nog in gebruik zijnde CAS-nummers, niet diegene die ik hier vraag om te schrappen. Ik vind deze wel terug op de website van Echa als "Other CAS number"
