### ISSUE TITLE
Aanmaken nieuwe sommatie_stof PCB t

### ISSUE THREAD

**Issue by J-meirlaen** [Informatievlaanderen/OSLOthema-omgeving#27]
Bij het omzetten naar de codelijsten is vmm par_id 445 gemapt bij PCB 169 https://data.omgeving.vlaanderen.be/doc/concept/chemische_stof/ZHLICBPIXDOFFG-UHFFFAOYSA-N

Dit moet een nieuwe stof worden
preflabel PCB totaal
https://data.omgeving.vlaanderen.be/id/concept/sommatie_stoffen/pcb_t
notation: PCB t
Analysemethode: https://reflabos.vito.be/2022/CMA_3_I.pdf

**Comment by gezever** [comment]
@J-meirlaen 
Je zou hier ook met de chemische ontologie kunnen werken.
https://data.omgeving.vlaanderen.be/id/concept/chemische_stof/CHEMONTID_0003030

**Comment by J-meirlaen** [comment]
@gezever : In de gekoppelde analysemethode staan 7 PCB's vermeld, die deel uitmaken van het totaal. De ontologie is dus niet specifiek genoeg. 
<img width="423" alt="image" src="https://github.com/Informatievlaanderen/OSLOthema-omgeving/assets/80043640/6b71d5dc-b097-47c7-a35e-49ccd5597a07">

**Comment by gezever** [comment]
@J-meirlaen 
In jullie parameterlijst zijn er verschillende.
<https://data.omgeving.vlaanderen.be/id/concept/eea_33-38-5> a ns1:Concept ;
    ns1:altLabel "PCB t"^^xsd:string ;
    ns1:exactMatch <http://dd.eionet.europa.eu/vocabulary/wise/ObservedProperty/EEA_33-38-5> ;
    ns1:inScheme <https://data.omgeving.vlaanderen.be/id/conceptscheme/parameter> ;
    ns1:narrower <https://data.omgeving.vlaanderen.be/id/concept/wise/ObservedProperty> ;
    ns1:notation "EEA_33-38-5" ;
    ns1:prefLabel "Polychlorinated biphenyls (7 PCB: 28,52,101,118,138,153,180)"@en,
        "Polychloorbifenyl, totaal"@nl ;
    ns3:status <http://dd.eionet.europa.eu/vocabulary/datadictionary/status/valid> ;
    ns2:eeaNummer "33-38-5"^^xsd:int ;
    ns2:vmmParameterId "445"^^xsd:int .

en 

<https://data.omgeving.vlaanderen.be/id/concept/cas_1336-36-3> a ns1:Concept ;
    rdfs:seeAlso <https://pubchem.ncbi.nlm.nih.gov/compound/36231> ;
    ns1:altLabel "PCB t"^^xsd:string ;
    ns1:broader <https://data.omgeving.vlaanderen.be/id/concept/wise/ObservedProperty> ;
    ns1:exactMatch <http://dd.eionet.europa.eu/vocabulary/wise/ObservedProperty/CAS_1336-36-3> ;
    ns1:inScheme <https://data.omgeving.vlaanderen.be/id/conceptscheme/parameter> ;
    ns1:notation "CAS_1336-36-3" ;
    ns1:prefLabel "Polychlorinated biphenyls"@en,
        "Polychloorbifenyl, totaal"@nl ;
    ns3:status <http://dd.eionet.europa.eu/vocabulary/datadictionary/status/valid> ;
    ns2:casNummer "1336-36-3"^^xsd:int ;
    ns2:vmmParameterId "445"^^xsd:int .

Ik neem aan dat je de eerste bedoelt.

**Comment by J-meirlaen** [comment]
@gezever : inderdaad de eerste, vermits de 7 vermelde PCB's identiek zijn.
