### ISSUE TITLE
Aanmaken sommatie stoffen Fenolen totaal

### ISSUE THREAD

**Issue by J-meirlaen** [Informatievlaanderen/OSLOthema-omgeving#29]
De parameter fenolen totaal ontbreekt in de sommatie stoffen lijst

PrefLabel:  Fenolen totaal
AltLabel: Phenols
Notation Fol t
http://dd.eionet.europa.eu/vocabulary/wise/ObservedProperty/CAS_64743-03-9
CAS 64743-03-9

**Comment by gezever** [comment]
@J-meirlaen 

- Phenols is ook een prefLabel in het engels
- nieuwe uri https://data.omgeving.vlaanderen.be/id/concept/sommatie_stoffen/fol_t
- zie ook https://data.omgeving.vlaanderen.be/id/concept/chemische_stof/CHEMONTID_0000134
