### ISSUE TITLE
Aanmaken Organochloorpesticden, totaal (IMJV)

### ISSUE THREAD

**Issue by J-meirlaen** [Informatievlaanderen/OSLOthema-omgeving#30]
De stof
Totaal organochloorpesticiden waarvan individuele drempelwaarde = 0,1 kg/jaar ontbreekt in de sommatie stoffen lijst.

prefLabel : "Organochloorpesticiden, totaal (IMJV)"
Notation: "OCP t (IMJV)"
AltLabel "Totaal organochloorpesticiden waarvan individuele drempelwaarde = 0,1 kg/jaar"

**Comment by gezever** [comment]
@J-meirlaen 
Deze bestaat al.
https://data.omgeving.vlaanderen.be/id/concept/sommatie_stoffen/ocp_t

**Comment by gezever** [comment]
aangemaakt:
https://data.omgeving.vlaanderen.be/id/concept/sommatie_stoffen/ocp_t_imjv
