### ISSUE TITLE
Aanmaken nieuwe parameters voor imjv lucht

### ISSUE THREAD

**Issue by J-meirlaen** [Informatievlaanderen/OSLOthema-omgeving#32]
Bij het mappen van de imjv parameters voor luchtemissies, stel ik vast dat volgende parameters ontbreken

Voor de codelijst Sommatie Stoffen

- Preflabel: "Perfluorkoolwaterstoffen (IMJV-lucht)", Altlabel: "PFKs", Definition "som van CF4, C2F6, C3F8, C4F10, c-C4F8, C5F12, C6F14"
- Preflabel "PM10", Definition: "fijn stof kleiner dan 10 µm"
- Preflabel "PM2,5", Definition: "fijn stof kleiner dan 2,5 µm"
- Preflabel "PM0,1", Definition: "fijn stof kleiner dan 0,1 µm" (niet voor het imjv, wel algemeen luchtkwaliteit)

Kunnen deze aangemaakt worden?

**Comment by gezever** [comment]
`css:pm10  a              skos:Concept;
        skos:broader     css:fijn_stof;
        skos:definition  "fijn stof kleiner dan 10 µm"@nl;
        skos:inScheme    vlcs:sommatie_stoffen;
        skos:notation    "PM10";
        skos:prefLabel   "PM10"@nl;
        dcat:theme       gemet:2912 , gemet:9214 .

css:pm0.1  a             skos:Concept;
        skos:broader     css:fijn_stof;
        skos:definition  "fijn stof kleiner dan 0,1 µm"@nl;
        skos:inScheme    vlcs:sommatie_stoffen;
        skos:notation    "PM0.1";
        skos:prefLabel   "PM0,1"@nl;
        dcat:theme       gemet:2912 , gemet:9214 .

css:pm2.5  a             skos:Concept;
        skos:broader     css:fijn_stof;
        skos:definition  "fijn stof kleiner dan 2,5 µm"@nl;
        skos:inScheme    vlcs:sommatie_stoffen;
        skos:notation    "PM2.5";
        skos:prefLabel   "PM2,5"@nl;
        dcat:theme       gemet:2912 , gemet:9214 .`

**Comment by gezever** [comment]
`css:pfk_imjv_lucht  a      skos:Concept;
        skos:altLabel      "PFKs"@nl;
        skos:broadMatch    csc:CHEMONTID_0001517;
        skos:broader       css:pft_t;
        skos:definition    "som van CF4, C2F6, C3F8, C4F10, c-C4F8, C5F12, C6F14"@nl;
        skos:inScheme      vlcs:sommatie_stoffen;
        skos:narrowMatch   csc:KAVGMUDTWQVPDF-UHFFFAOYSA-N , csc:QYSGYZVSCZSLHT-UHFFFAOYSA-N , csc:BCCOBQSFUDVTJQ-UHFFFAOYSA-N , csc:NJCBUSHGCBERSK-UHFFFAOYSA-N , csc:ZJIJAJXFLBMLCK-UHFFFAOYSA-N , csc:WMIYKQLTONQJES-UHFFFAOYSA-N;
        skos:notation      "PFK imjv";
        skos:prefLabel     "Perfluorkoolwaterstoffen (IMJV-lucht)"@nl;
        skos:topConceptOf  vlcs:sommatie_stoffen;
        dcat:theme         gemet:9214 , gemet:2912 .`

**Comment by gezever** [comment]
https://data.omgeving.vlaanderen.be/id/concept/sommatie_stoffen/pfk_imjv_lucht
https://data.omgeving.vlaanderen.be/id/concept/sommatie_stoffen/pm10
https://data.omgeving.vlaanderen.be/id/concept/sommatie_stoffen/pm2.5
https://data.omgeving.vlaanderen.be/id/concept/sommatie_stoffen/pm0.1

**Comment by J-meirlaen** [comment]
@gezever 
https://data.omgeving.vlaanderen.be/id/concept/sommatie_stoffen/pfk_imjv_lucht heeft als inkomende relatie [Collectie van verzameling stoffen die in water worden gemeten](https://data.omgeving.vlaanderen.be/id/collection/sommatie_stoffen/water). Dit moet geschrapt worden. Het theme is waterkwaliteit, terwijl het luchtkwaliteit moet zijn.

https://data.omgeving.vlaanderen.be/id/concept/sommatie_stoffen/pm10
https://data.omgeving.vlaanderen.be/id/concept/sommatie_stoffen/pm2.5
https://data.omgeving.vlaanderen.be/id/concept/sommatie_stoffen/pm0.1

hebben als als thema waterkwaliteit, wat niet correct is. Kan dit geschrapt worden?

**Comment by gezever** [comment]
@J-meirlaen 

Is aangepast.
