### ISSUE TITLE
Codetabel materiaaklasse: vraag bij ct:

### ISSUE THREAD

**Issue by ChandraAlgoe** [Informatievlaanderen/OSLOthema-omgeving#33]
In de DOV-codetabel materiaalklasse staat et ct:lucht en ct:water. Moet dit niet gewoon Lucht en Water zijn?

![image](https://github.com/Informatievlaanderen/OSLOthema-omgeving/assets/48786550/5ad355f4-98e2-4580-b640-6da8cb9148ed)

**Comment by timothy-debock** [comment]
foutje bij opstellen codelijst, dit wordt verwerkt in volgende versie

**Comment by ChandraAlgoe** [comment]
Was verkeerd gelogd.
Zie ook: https://github.com/bodemenondergrond/codelijst-materiaalklasse/issues/1
